### ISSUE TITLE
stroke sequence learning

### ISSUE THREAD

**Issue by deepseek** [megvii-research/ICCV2019-LearningToPaint#34]
@hzwer 
Can this method be trained not only to pain, but also to pain in a certain sequence?
i am interested in training a network to learn the sequence and order of the drawing and strokes.
any suggestions

**Comment by hzwer** [comment]
Designing a reward that is related to the order (such as arranging the starting points of strokes from left to right) may be able to train such a model.

**Comment by deepseek** [comment]
The question is, can i teach the model the context order of objects in an image.
example

![0](https://user-images.githubusercontent.com/49877135/84778154-3d5e7f80-afeb-11ea-8f3d-7f8d7f12bbdf.gif)
