### ISSUE TITLE
Different Neural Renderer

### ISSUE THREAD

**Issue by yasminezakaria** [megvii-research/ICCV2019-LearningToPaint#35]
Hello @hzwer,
Kindly, I have 2 questions:-

1. I noticed you provided extra renderers in the README file. What modifications did you apply to the stroke_gen file so that you could train those renderers?
2. What bezierwotrans.pkl --- actor_notrans.pkl files names stand for?

Thanks in advance

**Comment by hzwer** [comment]
1. baseline/Renderer/stroke_gen.py is a renderer that can draw bezier curve now. If you want to draw a triangle, you can make the parameter of draw represent the vertices of the triangle and call the cv2 interface to draw a triangle.
2. We set up an experiment where the renderer has no transparency control. The actor_notrans.pkl save the actor parameters trained under this setting.
