### ISSUE TITLE
how wgan is trained??

### ISSUE THREAD

**Issue by kenoharada** [megvii-research/ICCV2019-LearningToPaint#36]
Thank you for sharing your awesome work!

In your paper, you mentioned that using wgan discriminator loss to define the reward.

But how wgan is trained in your work?(pre-train to some extent beforehand and using in [cal_dis](https://github.com/megvii-research/ICCV2019-LearningToPaint/blob/2ff7b6b02a47c21124f60be7462a89546ce77077/baseline/env.py#L100)??)

**Comment by hzwer** [comment]
WGAN is trained from scratch during RL training. In short, we regard Paintings as fake examples, the target images as real  examples.
In other words, RL painter is a generator, we fight against training a discriminator.

**Comment by kenoharada** [comment]
Thank you very much for answering!
I got it!
