### ISSUE TITLE
Stroke gen

### ISSUE THREAD

**Issue by ChrisSsak** [megvii-research/ICCV2019-LearningToPaint#41]
Hi, looking at the draw() function it seems like the generator creates greyscale brushstrokes. Where do the colour parameters get inputted?

**Comment by hzwer** [comment]
Please refer to https://github.com/megvii-research/ICCV2019-LearningToPaint/blob/83dc2b6129feeeb56a0cb1fd91d3ffdb9d288616/baseline/DRL/ddpg.py#L30.

We expand the strokes into three channels and multiply each by the color value.

**Comment by ChrisSsak** [comment]
Thank you
