### ISSUE TITLE
Training parameters

### ISSUE THREAD

**Issue by patrisaru** [megvii-research/ICCV2019-LearningToPaint#43]
Hi !

I am trying to train the paint agent in my GPU. In the paper I could read that the training time was about 2 days in your case. 

Can you tell me what parameters used you to train the paint agent? In my case the training time is more than 1 week (I am training the agent in a GPU too but I think that there is a lot of time difference).

Thanks so much!

**Comment by hzwer** [comment]
Hi, I use the default parameter and train the agent on a 2080Ti GPU. I think you can try python-CProfile to check whether there is a bottleneck in the data generator.
