### ISSUE TITLE
What is the difference between `baseline` and `baseline_modelfree`?

### ISSUE THREAD

**Issue by UdonDa** [megvii-research/ICCV2019-LearningToPaint#45]
Hi, I have a question about your directory structure.

What is the difference between `baseline` and `baseline_modelfree`?

I think that they look the same.

Would you teach me the difference?

**Comment by hzwer** [comment]
Hi! I'sorry to replay you so late.
The difference between the two is whether the renderer can conduct gradients. In other words, the model-free version requires the critic to model this painting task according to reward.
