### ISSUE TITLE
notrans renderer weights loading error

### ISSUE THREAD

**Issue by yasminezakaria** [megvii-research/ICCV2019-LearningToPaint#47]
Hello @hzwer 
i have a problem loading notrans renderer weights while using test.py file
here is a screenshot of the error
<img width="837" alt="Screen Shot 2021-01-03 at 8 23 00 PM" src="https://user-images.githubusercontent.com/24360248/103485775-80eece80-4e01-11eb-903c-df74db123a47.png">
Do i need to change anything in the code?

**Comment by hzwer** [comment]
It seems that the pkl data is damaged.
