### ISSUE TITLE
stroke 

### ISSUE THREAD

**Issue by supermy777** [megvii-research/ICCV2019-LearningToPaint#50]
I want to get the final stroke parameters! What should I do? please! Thank you!

**Comment by hzwer** [comment]
I am very sorry that I did not see your message.
You may return every stroke and its parameters in this function.
 https://github.com/megvii-research/ICCV2019-LearningToPaint/blob/24e317ba1d7c88435677fc77cb2ded6d03b2a914/baseline/DRL/ddpg.py#L36
