### ISSUE TITLE
How to change strokes?

### ISSUE THREAD

**Issue by neverstoplearn** [megvii-research/ICCV2019-LearningToPaint#51]
the readme.md said A step contains 5 strokes in default,when I train another model,where i can change strokes?

**Comment by hzwer** [comment]
https://github.com/megvii-research/ICCV2019-LearningToPaint/blob/24e317ba1d7c88435677fc77cb2ded6d03b2a914/baseline/DRL/ddpg.py#L33
I am very sorry that I did not see your message
