### ISSUE TITLE
How to make L2 rewards work?

### ISSUE THREAD

**Issue by Papur1ka** [megvii-research/ICCV2019-LearningToPaint#52]
I have tried to use L2 reward in ddpg.py line 102 and cancel WGAN optimization, but after the same iterations, this painter is not as good as WGAN reward.
Kindly, how do you make L2 rewards work?

**Comment by hzwer** [comment]
Hi, as shown in our paper, l2 reward can not get same performance as WGAN reward. Please refer to SPIRAL paper for more details. https://arxiv.org/abs/1804.01118, supplementary
<img width="549" alt="image" src="https://user-images.githubusercontent.com/10103856/123897552-268c9000-d996-11eb-836d-a759a4488b45.png">
Maybe l1 reward will be better.
