### ISSUE TITLE
Question about brush stroke texture

### ISSUE THREAD

**Issue by ugocapeto** [megvii-research/ICCV2019-LearningToPaint#54]
This is a terrific project. Being able to generate so few strokes is quite an achievement.

Is it possible to use a textured brush stroke?

What I mean is using a grayscale picture of a real brush stroke. The grayscale value in the picture gives the transparency.

See for example this blog post
http://3dstereophoto.blogspot.com/2018/07/non-photorealistic-rendering-software.html
that describes a "classic" (not AI) Stroke Based Renderer

**Comment by hzwer** [comment]
You may refer to some recent work, 
https://github.com/jiupinjia/stylized-neural-painting
https://github.com/wzmsltw/PaintTransformer
