### ISSUE TITLE
Question about reward

### ISSUE THREAD

**Issue by aemior** [megvii-research/ICCV2019-LearningToPaint#55]
I find the reward save to Replay buffer https://github.com/megvii-research/ICCV2019-LearningToPaint/blob/24e317ba1d7c88435677fc77cb2ded6d03b2a914/baseline/env.py#L105 is different from the reward calculate in training process https://github.com/megvii-research/ICCV2019-LearningToPaint/blob/24e317ba1d7c88435677fc77cb2ded6d03b2a914/baseline/DRL/ddpg.py#L102 ，one is divide by initial distance and one is not, is it a bug? or it's just ok

**Comment by hzwer** [comment]
Hi! During model training, the reward from environment is not used and the wgan distance is actually used to guide the agent. The reward from environment is just used for observing the training process.

**Comment by aemior** [comment]
Thanks, I got it.
