### ISSUE TITLE
Question about Q value

### ISSUE THREAD

**Issue by zxyam** [megvii-research/ICCV2019-LearningToPaint#56]
I love this amazing project. I'm surprised that neural networks can do such incredible thing.
There is a small problem about Q value. In the paper cur_q = reward + γ * target_q, so normally it should be "return Q, gan_reward" in evaluate(). This is actually the case in model-free method. But in model-based method it's "return (Q+gan_reward), gan_reward", this makes me confused. Why does the Q value need to be added with the reward of the same step?

**Comment by hzwer** [comment]
Q+reward is actually the Q value of the DDPG algorithm theory. My initial idea is that since I have the reward of the current step, the critic only needs to estimate a delta.
