### ISSUE TITLE
关于其他数据集的问题

### ISSUE THREAD

**Issue by Donkdot** [megvii-research/ICCV2019-LearningToPaint#59]
您好！我在使用CUB Birds 和 Stanford cars数据集进行训练时，图片只显示一个颜色，随着训练过程进行也没有其他变化，我对代码的修改仅有load_data(), 为什么会造成这种情况呢？

**Comment by hzwer** [comment]
你好，按理说一开始模型的输出如果是随机的，那颜色也应该是各种都有。
是不是有可能你的输入图片范围变成了 0-255 ？
如果说只换了数据集，我暂时想不到其它的可能问题。

**Comment by Donkdot** [comment]
好的，我再检查一下，感谢您的回复！
